[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@cartesi/=node_modules/@cartesi/"]
solc_version = "0.8.24"
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
